# 返回的自定义异常信息的 dict
USER_ALREADY_EXISTS = 20001  # 用户已经存在

err_msg = {
    USER_ALREADY_EXISTS: 'user already exists'
}